### ISSUE TITLE
Real World Simulation

### ISSUE THREAD

**Issue by anywhichway** [aduth/memize#12]
Most memoization libraries test repeated calls using the same arguments that guarantee memoized cache hits. In the real world this is unlikely. For a real world simulation where only 20% of the function calls are memoized and they take and return mixed argument types the performance results do not seem to match your claims. Of course, my simulation could be wrong. As you poiunt out in your README, there is a resonable expectations that memoization should be stack oriented since the intent could be to prevent multiple requests for the same argument signature. Also, under the simulation the variability of response time for memize can be quite high. In some situations, this might be considered a bad thing.

|  nanomemoizedFunctions    |  2,172,477  |  ± 2.63%                   |  81           | 
|  moizeMemoizedFunctions   |  1,279,591  |  ± 2.30%                   |  83           | 
|  microMemoizedFunctions   |  1,206,613  |  ± 2.62%                   |  81           | 
|  fastMemoizedFunctions    |  441,783    |  ± 2.94%                   |  79           | 
|  memizeMemoizedFunctions  |  3,727      |  ± 34.45%                  |  9            | 

see: https://github.com/anywhichway/nano-memoize/blob/master/benchmark/real-world-simulation.js

**Comment by aduth** [comment]
Hi 👋 

Memize intentionally optimizes for scenarios where there's repeated calls with the same arguments. This was mentioned in the README, though admittedly buried in the content. I restructured the content in d461490c68defae4923fb5b54475c42ba4182417 to do a few things, which I hope address your comments:

* Call out the optimization scenarios early in the README.
* Drop the claim of being "the fastest". I'm not engaged enough in this project anymore to care to defend the title.
* Remove the benchmark results from the top-level README. I kept them in the `benchmark/` folder as a historical artifact, but added some important disclaimers about them being both outdated and based on a fairly naive benchmark script implementation.

**Comment by anywhichway** [comment]
I think you are premature in dropping the "fastest" claim. Although I have identified some minor optimizations in my code, I have done some very thorough testing and with the exception of my "real world" simulation (which could be way off), you remain the overall fastest. I will be updating my docs to point to your repo for people that simply want speed and do not need configuration options and perhaps dropping the "real-world" stuff.

This being said, I am very puzzled by the really low performance of your code in my "real world" simulation. I might expect your code to align with `moize` or `micro-memoize` but to be over 100x slower seems really odd!

I have no idea why I missed your library in the past! Only reason I wrote mine was the author of `fast-memoize` originally claimed his was the "fastest possible", he included the word "attempt" after I prodded him a little. It is fascinating so many people have adopted his library, although it is pretty clean from an architecture perspective (as is yours), mine is a bit obscure.

**Comment by aduth** [comment]
Yeah, my concern with the "fastest" label is more that it ends up being a lightning rod for attention that I'm not prepared to keep up with, is highly dependent on the circumstances of the code (as you've pointed out), and requires me to keep up with the latest tools in the space for the claim to be accurate.

I'd have to take a closer look to understand what's going on with the slow results. Based on the implementation, I could imagine that without a maximum cache size, and with total randomness of arguments, it could run the risk of growing quite slow, since it could start to have to iterate through a large cache for each cache miss. In those cases, it might make more sense to either set a maximum cache size, not memoize at all, or find another tool more optimized to those scenarios.

If I'm following your benchmark code correctly, I could see how that might happen with [passing a new object each time](https://github.com/anywhichway/nano-memoize/blob/1e208637d0fe291c3205f6fe077e02a369edcb49/benchmark/real-world-simulation.js#L186), since Memize can only cache by same object reference, not deep equality.

**Comment by anywhichway** [comment]
Thanks for your explanation.
