### ISSUE TITLE
Custom argument serializer (Object argument support)

### ISSUE THREAD

**Issue by NamesMT** [aduth/memize#15]
Nowadays most function takes an object as their argument, like: `funcA({ a: 1, b: 2})`  
Currently, even if the object looks the same, memize will always execute a new function as the object reference is not equal.

A custom serializer option for argument will solve this.

**Comment by NamesMT** [comment]
A basic example with a custom serializer:
`memize(funcA, { serializer: JSON.stringify })`

**Comment by aduth** [comment]
Hi @NamesMT 👋 Thanks for the suggestion.

To help me understand the use-case, would you be able to provide a more realistic example of how you might want to use this in a project?

**Comment by NamesMT** [comment]
Hi @aduth,
The use-case could applies to generally any function, if they expects a config object instead of primitive arguments then `memize` does not currently work, here is my example:
```ts
async function _useUserSettings<T extends Record<string, any>>(key: string, schema: T) {
  // // This function is redacted but basically it is basically the following:
  // Load current settings from API
  const currentSettings = callApi(key, schema)

  // Set up reactivity hooks for the settings object, changes will automatically be pushed to server
  const hookedSettings = setupHooks(currentSettings)

  return { data: hookedSettings }
}
export const useUserSettings = memize(_useUserSettings) // memize cannot support this function, all calls even with same key and schema will cause the API to be recalled

// In this example, the API is called twice:
const uiSettings = await useUserSettings('UI', { locale: 'en' })
const uiSettings2 = await useUserSettings('UI', { locale: 'en' })
```

**Comment by aduth** [comment]
Thanks for sharing the example. After considering it a bit more, I don't think I'll plan to add this feature right now. I've intentionally kept this project very feature-light, which has allowed me to squeeze the most out of performance and package size.

For your example, a few ideas you could consider:

- If your `callApi` supports it, you could "preserialize" the argument passed to the memoized function
   - `await useUserSettings('UI', JSON.stringify({ locale: 'en' }))`
- You could construct the object within the memoized function and pass primitive arguments
   - `await useUserSettings('UI', 'en')`
- If your build pipeline supports it, you could use [a Record object, a TC39 Stage 2 proposal](https://github.com/tc39/proposal-record-tuple)
   - `await useUserSettings('UI', #{ locale: 'en' })`
- If all else fails, another memoization library might offer this functionality. I list a handful in the [benchmarks README](https://github.com/aduth/memize/tree/master/benchmark). One that has something like this is `memoizee` and [its `normalizer` argument](https://github.com/medikoo/memoizee?tab=readme-ov-file#writing-custom-cache-id-normalizers). One potential gotcha with this approach to normalization is property ordering, since e.g. `JSON.stringify({ a: 1, b: 2 }) !== JSON.stringify({ b: 2, a: 1 })`
