### ISSUE TITLE
jsperf links 404

### ISSUE THREAD

**Issue by timelsass** [aduth/memize#2]
readme's jsPerf links: 
https://jsperf.com/lookup-json-stringify-vs-shallow-equality 
https://jsperf.com/array-unshift-linked-list

These lead to 404s.  Perhaps a couple of additional benchmark tests to cover those comparisons would be a viable alternative to avoid this happening in the future since jsperf uses benchmark.js anyways?

**Comment by aduth** [comment]
Yes, it's unfortunate that JSPerf has been unreliable for some time now. Including the benchmarks in the codebase could be an option, or even just pointing to some Gist files, or perhaps there's a more reliable service for hosted benchmarking I could point to instead of JSPerf.

**Comment by aduth** [comment]
I think JSPerf must have deleted or lost them at some point. I didn't have a backup of the benchmarks, but I recreated them from memory based on what I assumed to demonstrate. Since those pages were previously 404, I was able to reclaim the existing slugs and didn't need to push any updates to the repository.
