### ISSUE TITLE
Custom equality function

### ISSUE THREAD

**Issue by pkuliga** [aduth/memize#9]
Hi, is it possible to add a custom equality function as an option similar to what [memoize-one](https://www.npmjs.com/package/memoize-one#user-content-custom-equality-function) has?

At the moment I have both `memize` and `memoize-one` in my project and after this function is added I could get rid of `memoize-one` for good.

**Comment by aduth** [comment]
Hi @pkuliga , could you give an example use-case where this sort of feature would be used?

Typically I hesitate to add new features since this library is intentionally feature-light, both to keep the bundle size small and because the performance relies on very particular implementation optimizations that makes it difficult to add features.

I wonder if it would be possible to achieve what you're after with some intermediary function call, but I'd need to understand more how you're looking to use it.

**Comment by pkuliga** [comment]
Sure, for example here:
```js
const fn = ({ a }) => {
    return { a: a * 2 };
}

const mfn = memize(fn);

mfn({a: 5});
mfn({a: 5});
```
The `fn` function will be executed twice, which is not what I want.

With the custom equality function I would be able to do sth like this:
```js
const fn = ({ a }) => {
    return { a: a * 2 };
}

const mfn = memize(fn, { isEqual: lodash.isEqual });

mfn({a: 5});
mfn({a: 5});
```
With deep comparison provided by `lodash.isEqual` the `fn` function should be executed only once.

**Comment by aduth** [comment]
Thanks for the sharing that example. I think at this time it won't be a feature I'd plan to add, because of the reasons mentioned in my previous comment.

I might suggest a couple alternatives to consider, though:

1. Creating a wrapper which converts the arguments to a primitive value which can be compared using the default equality check
2. Use [experimental Record type](https://tc39.es/proposal-record-tuple/tutorial/) for object-like argument that can do strict equality check
3. Consider a more feature-focused memoization library, like some of the ones mentioned in [the Benchmarks section](https://github.com/aduth/memize#benchmarks)

A wrapper could look like this, for example:

```js
function memizeObj(fn) {
    const memoizedFn = memize((str) => fn(JSON.parse(str)));
    return (obj) => memoizedFn(JSON.stringify(obj));
}
```

Or maybe like this, using another library of mine, [`equivalent-key-map`](https://github.com/aduth/equivalent-key-map):

```js
function memizeObj(fn) {
    const memoizedFn = memize(fn);
    const map = new EquivalentKeyMap();
    return (obj) => {
        let arg = map.get(obj);
        if (!arg) {
            arg = obj;
            map.set(obj, arg);
        }
        return memoizedFn(arg);
    };
}
```
